/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'fern' at '5/28/16 9:06 AM' with Gradle 2.8
 *
 * @author fern, @date 5/28/16 9:06 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
