/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fern' at '5/28/16 9:40 PM' with Gradle 2.8
 *
 * @author fern, @date 5/28/16 9:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
